site_name: 三木奇奇怪怪的文档收录
site_url: https://docs.529300529.xyz
site_description: >-
  各种文档、记录整理收录合集

repo_name: Samuel-0-0/docs/
repo_url: https://github.com/Samuel-0-0/docs/
theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
    - Home: index.md
    - VAST系列产品手册:
      - Voron 0.2裙边按钮+屏幕套件: vast/v0_skirt/readme.md
      - Voron 0.2集线板+主控板套件: vast/v0_D4/readme.md
      - 电源计量与远程控制: vast/power/readme.md
      - SB头内嵌CAN控制板: vast/sb_can/readme.md
      - 挤出与热端水冷一体套件(含CAN驱动板): vast/water/readme.md
    - 3D打印机相关:
      - 打印机安装调试:
        - Voron 0.2: 3d_printer/voron/v0.md
        - Voron 2.4: 3d_printer/voron/v2.4.md
      - Klipper安装及使用: 3d_printer/klipper.md
      - 打印及切片软件调试: 3d_printer/slicer.md
