site_name: 三木奇奇怪怪的文档收录
site_url: https://docs.529300529.xyz
site_description: >-
  各种文档、记录整理收录合集

repo_name: Samuel-0-0/docs/
repo_url: https://github.com/Samuel-0-0/docs/

# 导航栏
nav:
    - Home: index.md
    - VAST系列产品手册:
      - Voron 0.2裙边按钮+屏幕套件: vast/v0_skirt/readme.md
      - Voron 0.2集线板+主控板套件: vast/v0_D4/readme.md
      - 电源计量与远程控制: vast/power/readme.md
      - Stealthburner内嵌CAN控制板: 
        - 概述: vast/sb-can/index.md
        - Canboot(可选): vast/sb-can/canboot.md
        - Klipper: vast/sb-can/klipper.md
      - 挤出与热端水冷一体套件(含CAN驱动板): vast/water/readme.md
    - 3D打印机相关:
      - 打印机安装调试:
        - Voron 0.2: 3d_printer/voron/v0.md
        - Voron 2.4: 3d_printer/voron/v2.4.md
      - Klipper安装及使用:
        - 图形化一键脚本: 3d_printer/klipper/assistant.md
        - 7寸触屏小主机: 3d_printer/klipper/7.md
        - 其他: 3d_printer/klipper/klipper.md
      - 打印及切片软件调试: 3d_printer/slicer.md

plugins:
  - search

theme:
  name: material
  language: zh
  # 主题颜色
  palette:
    # 明亮模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换到暗黑模式
    # 暗黑模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到明亮模式
  # 特征
  features:
    # 代码块复制按钮
    - content.code.copy
    # 代码块注解，使用方法：在代码要加注解的后面加"# (1)"
    # 然后在代码后面加"1.  注解的内容"
    - content.code.annotate
    # 导航全部展开
    - navigation.indexes
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

# markdowm扩展
markdown_extensions:
  # 警示栏
  - admonition
  # 警示栏可折叠
  - pymdownx.details
  - md_in_html
  # 代码块
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # 列表
  - def_list
  # 任务列表
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: |
  &copy; 2023 <a href="https://github.com/Samuel-0-0"  target="_blank" rel="noopener">Samuel Wang (三木)</a>
